name: Build Documentation

on:
  push:
    branches:
      - master
    paths:
      - src/**
      - README.md
      - typedoc.json

jobs:
  TypeDoc:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: 10

      - name: Installing dependencies and generating documentation
        run: npm install && npm run docs

      - name: Publishing to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: docs/